"""Identify a generated final report through its existing acceptance chain.

The default dirty classifier remains conservative. Only a successful delivery
may attribute its own receipt-bound report to Stage 10; authored mathematics,
unbound reports and earlier-stage reports retain their original ownership.
"""
from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path

from .audit.acceptance import verify_final_acceptance_receipt
from .audit.domain import AuditSnapshot
from .domain import InvalidTransition, SCHEMA_VERSION
from .workflow_events import canonical_hash


def _sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def verified_final_report(project):
    project = Path(project).resolve()
    try:
        latest = json.loads((project / '.factory/audits/latest.json').read_text())
        sid = latest['snapshot_id']
        if (not re.fullmatch(r'[0-9a-f]{64}', sid)
                or latest.get('status') != 'PASS'
                or latest.get('profile') != 'final'
                or latest.get('override') is not False
                or latest.get('judge_completed') is not True
                or latest.get('delivery_allowed') is not True):
            return None
        snapshot = AuditSnapshot(**json.loads(
            (project / '.factory/audits' / sid / 'snapshot.json').read_text()))
        valid, _ = verify_final_acceptance_receipt(
            project, snapshot, expected_snapshot_id=sid, expected_status='PASS')
        if not valid:
            return None
        receipt_path = project / 'judge_outputs/judgment_receipt.json'
        receipt = json.loads(receipt_path.read_text())
        report = receipt['derived_artifacts']['report']
        if (receipt.get('schema') != 'judgment-receipt-v1'
                or receipt.get('status') != 'VALID'
                or receipt.get('input_fingerprint') != sid
                or receipt.get('decision', {}).get('effective_decision') != 'PASS'
                or report.get('path') != 'judge_evaluation.md'):
            return None
        path = project / 'judge_evaluation.md'
        if (report.get('bytes') != path.stat().st_size
                or report.get('sha256') != _sha(path)):
            return None
        return {
            'schema_version': 'factory-final-judge-projection-v1',
            'snapshot_id': sid, 'report': report,
            'judgment_receipt_sha256': _sha(receipt_path),
            'final_acceptance_sha256': _sha(project / 'judge_outputs/final_acceptance_receipt.json'),
            'quality_override': False,
        }
    except (OSError, ValueError, KeyError, TypeError):
        return None


def classify_delivery_report(project, task, changes):
    if (task.stage_id, task.source_step_id, task.subtask) != (10, 16, 'delivery'):
        return changes
    if any((int(item['owner_stage']) < 10
            and item['cause_artifact'] != 'judge_evaluation.md')
           or (item['cause_artifact'].startswith('@protected:')
               and item['current_fingerprint'] == 'MISSING')
           for item in changes):
        return changes
    candidates = [item for item in changes if item['cause_artifact'] == 'judge_evaluation.md']
    if not candidates:
        return changes
    proof = verified_final_report(project)
    if proof is None:
        return changes
    return [
        {**item, 'flag': 'FORMAT_DIRTY', 'owner_stage': 10,
         'generated_projection_receipt': proof}
        if item['cause_artifact'] == 'judge_evaluation.md'
        and item['current_fingerprint'] == proof['report']['sha256']
        else item
        for item in changes
    ]


def preserve_verified_final_report(project):
    """Keep original receipt bytes before a later native audit replaces them."""
    project = Path(project).resolve()
    proof = verified_final_report(project)
    if proof is None:
        raise InvalidTransition('cannot preserve an unverified final report')
    target = project / '.factory/generated_judge_reports' / proof['report']['sha256']
    target.mkdir(parents=True, exist_ok=True)
    data = (project / 'judge_outputs/judgment_receipt.json').read_bytes()
    receipt_path = target / 'judgment_receipt.json'
    if receipt_path.exists() and receipt_path.read_bytes() != data:
        raise InvalidTransition('historical final report receipt already differs')
    receipt_path.write_bytes(data)
    if historical_final_report(project, proof['report']['sha256']) is None:
        raise InvalidTransition('historical report is not anchored to a published PASS release')
    return proof


def historical_final_report(project, report_sha):
    """Bind old generated bytes to an immutable, actually published release."""
    project = Path(project).resolve()
    if not re.fullmatch(r'[0-9a-f]{64}', report_sha):
        return None
    try:
        cached = project / '.factory/generated_judge_reports' / report_sha / 'judgment_receipt.json'
        receipt = json.loads(cached.read_text())
        sid = receipt['input_fingerprint']
        if not re.fullmatch(r'[0-9a-f]{64}', sid):
            return None
        release = project.parent.parent / 'papers/releases' / project.name / sid
        manifest = json.loads((release / 'delivery_manifest.json').read_text())
        unsigned = {k: v for k, v in manifest.items() if k != 'content_sha256'}
        if (manifest.get('schema_version') != 'paper-factory-release-v1'
                or manifest.get('snapshot_id') != sid or manifest.get('status') != 'PASS'
                or manifest.get('content_sha256') != canonical_hash(unsigned)):
            return None
        for key in ('audit_result', 'final_audit_receipt'):
            artifact = manifest['artifacts'][key]
            path = release / artifact['path']
            if path.parent != release or artifact['sha256'] != _sha(path) or artifact['bytes'] != path.stat().st_size:
                return None
        audit = json.loads((release / manifest['artifacts']['audit_result']['path']).read_text())
        acceptance = json.loads((release / manifest['artifacts']['final_audit_receipt']['path']).read_text())
        report = receipt['derived_artifacts']['report']
        if (audit.get('snapshot_id') != sid or audit.get('status') != 'PASS'
                or audit.get('override') is not False or audit.get('judge_completed') is not True
                or acceptance.get('snapshot_id') != sid or acceptance.get('status') != 'PASS'
                or acceptance['artifacts']['judgment_receipt']['sha256'] != _sha(cached)
                or acceptance['artifacts']['judgment_receipt']['bytes'] != cached.stat().st_size
                or receipt.get('status') != 'VALID' or receipt.get('schema') != 'judgment-receipt-v1'
                or report.get('path') != 'judge_evaluation.md' or report.get('sha256') != report_sha):
            return None
        return {'snapshot_id': sid, 'report_sha256': report_sha,
                'judgment_receipt_sha256': _sha(cached),
                'published_manifest_sha256': _sha(release / 'delivery_manifest.json')}
    except (OSError, ValueError, KeyError, TypeError):
        return None


def reclassify_recorded_report_cause(connection, project, dirty, *, revision, now, checkpoint):
    """Retain historical causes and record correction of this exact projection.

    This runs inside the existing successful Stage transition transaction. It
    never creates a success checkpoint and never clears unrelated obligations.
    """
    proof = dirty.get('generated_projection_receipt')
    if proof is None:
        return
    if (not checkpoint or checkpoint.get('stage_id') != 10
            or checkpoint.get('source_step_id') != 16
            or checkpoint.get('subtask') != 'delivery'
            or checkpoint.get('receipt', {}).get('status') != 'PASS'
            or dirty.get('cause_artifact') != 'judge_evaluation.md'
            or dirty.get('flag') != 'FORMAT_DIRTY' or dirty.get('owner_stage') != 10
            or verified_final_report(project) != proof
            or dirty.get('current_fingerprint') != proof['report']['sha256']):
        raise InvalidTransition('final report ownership correction lacks a valid delivery receipt')
    active = connection.execute(
        "SELECT * FROM dirty_flags WHERE flag='MATH_DIRTY' AND owner_stage=8").fetchone()
    if active is None:
        return
    last_clear = connection.execute(
        "SELECT COALESCE(MAX(revision),0) FROM dirty_flag_clear_receipts "
        "WHERE flag='MATH_DIRTY' AND owner_stage=8").fetchone()[0]
    causes = connection.execute(
        "SELECT * FROM dirty_causes WHERE flag='MATH_DIRTY' AND owner_stage=8 "
        "AND cause_revision>?", (last_clear,)).fetchall()
    historical = {}
    for row in causes:
        old_hash = row['current_fingerprint']
        if old_hash != proof['report']['sha256']:
            historical[old_hash] = historical_final_report(project, old_hash)
    if (not causes or active['cause_artifact'] != 'judge_evaluation.md'
            or not any(row['cause_revision'] == active['cause_revision']
                       and row['current_fingerprint'] == active['current_fingerprint']
                       for row in causes)
            or any(row['cause_artifact'] != 'judge_evaluation.md' for row in causes)
            or any(value is None for value in historical.values())):
        raise InvalidTransition('unrelated mathematical dirty causes require their original review')
    correction = {
        'schema_version': 'factory-final-judge-projection-reclassification-v1',
        'revision': revision, 'projection_receipt': proof,
        'historical_projection_receipts': historical,
        'corrected_cause_ids': sorted(row['cause_id'] for row in causes),
        'old_classifier_sha256': sorted({row['classifier_contract_sha256'] for row in causes}),
        'new_classifier_sha256': dirty['classifier_contract_sha256'],
        'remaining_obligation': {'flag': 'FORMAT_DIRTY', 'owner_stage': 10},
        'quality_override': False, 'new_success_receipts': 0,
    }
    connection.execute(
        'INSERT INTO dirty_classifier_rebases VALUES (?, ?, ?, ?, ?, ?, ?, ?)',
        (canonical_hash(correction), SCHEMA_VERSION, SCHEMA_VERSION,
         json.dumps(correction['old_classifier_sha256']), dirty['classifier_contract_sha256'],
         1, now, json.dumps(correction, ensure_ascii=True, sort_keys=True)))
    connection.execute("DELETE FROM dirty_flags WHERE flag='MATH_DIRTY' AND owner_stage=8")
